make permission changes recursive
fix:  There was an error while trying to write to `/srv/jekyll/Gemfile.lock`. It is
likely that you need to grant write permissions for that path.
Error: Process completed with exit code 23.